### ISSUE TITLE
Improve speed

### ISSUE THREAD

**Issue by varenius** [varenius/se_go_rank_calculator#1]
According to email exchange from Robert Åhs (who wrote the initial version of this code) the code might be improved with better speed:

Robert 19 aug 2013:
Jag upptäckte att man kan hämta alla turneringar och partier i ett anrop.
Man får med allt som behövs, utom turneringsklass (A eller B för full eller
halvpoäng). Dessa kan dock hämtas med ett extra anrop.

Man gör ett post-anrop till Player_Card.php med parametern switch_panel = 3..
Här är ett exempel i javascript:
$.ajax({ url:
"http://www.europeangodatabase.eu/EGD/Player_Card.php?&key=14986906", data: {
switch_panel: 3 }, success: function(r) { console.log(r); } })

Utnyttjar man detta borde det bli många gånger effektivare.

**Comment by freidrichen** [comment]
This has been implemented already.
