### ISSUE TITLE
More feedback on selected EGD PIN

### ISSUE THREAD

**Issue by varenius** [varenius/se_go_rank_calculator#3]
Currently one writes an EGD PIN and press search. This may return results, but there is no feedback on who the player actually is. It would be nice to get a field of "Found player NAME, COUNTRY, RANK" optionally with photo, to confirm one typed in the correct PIN.

**Comment by freidrichen** [comment]
Fixed in 319a71a544a4d509c46b29b5b5432a6bec4a5a2a
